### ISSUE TITLE
Create a SAM template with Powertools support bake in

### ISSUE THREAD

**Issue by msailes** [awslabs/aws-lambda-powertools-java#101]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

I'd like to use 'sam init' to create a java project which comes with Powertools included.

**Describe alternatives you've considered**

Maybe it should live in the SAM project? I think it would also do well here so it can be maintained in the same release cycles.

**Additional context**

An example would be the Python SAM template - https://github.com/aws-samples/cookiecutter-aws-sam-python

**Comment by dgomesbr** [comment]
Hey @msailes do we want a cookiecutter or a maven archetype?

**Comment by msailes** [comment]
A SAM cookiecutter would be best to start with. But I'd definitely take a maven archetype as well!

**Comment by vitodegiosa** [comment]
@msailes would this be possible just extracting the example/ directory from this repository and make a cookie cutter out of it?

**Comment by pankajagrawal16** [comment]
> @msailes would this be possible just extracting the example/ directory from this repository and make a cookie cutter out of it?

@vitodegiosa Yes that could be used as a starting point. But it will require some cleaning on terms of removing some of the extra logic and probably having separate cookie cutter project with maven and gradle

**Comment by vitodegiosa** [comment]
> > @msailes would this be possible just extracting the example/ directory from this repository and make a cookie cutter out of it?
> 
> @vitodegiosa Yes that could be used as a starting point. But it will require some cleaning on terms of removing some of the extra logic and probably having separate cookie cutter project with maven and gradle

@pankajagrawal16 I have something ready to go. Single cookie cutter project with possibility to select maven or gradle for dependency management and including only core utilities (metrics, logging, tracing). Should I create a new repo in awslabs? Should we agree on the name of the repo? cookiecutter-aws-sam-powertools-java? Too long?

**Comment by pankajagrawal16** [comment]
@vitodegiosa Great to hear. I would recommend putting in [aws-samples](https://github.com/aws-samples?q=cookie&type=&language=) instead along with other cookiecutter templates ?

**Comment by pankajagrawal16** [comment]
When it comes to naming, I am quite ok with long names as well, as long as it follows similar naming convention like others. Finally it will be replaced with names customers choose anyways during sam init. What do you think ? @vitodegiosa

**Comment by vitodegiosa** [comment]
done https://github.com/aws-samples/cookiecutter-aws-sam-powertools-java

**Comment by pankajagrawal16** [comment]
Thanks for the contribution again @vitodegiosa 🙌
