### ISSUE TITLE
AWS Lambda Powertools for Java: Idempotency - allow customised/improved object mapper

### ISSUE THREAD

**Issue by AlanStill** [awslabs/aws-lambda-powertools-java#1039]
**Is your feature request related to a problem? Please describe.**
The payload that I wish to use as my IdempotentKey contains an OffsetDateTime object. This generates the following exception.

"Java 8 date/time type `java.time.OffsetDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling"

Ordinarily this would be a simple matter of registering the JavaTimeModule with the ObjectMapper. However, as Idempotency usingthe JsonConfig.get().getObjectMapper() )I don't think this is currently possible.

**Describe the solution you'd like**

Is it possible to enhance the ObjectMapper that is used via the Idempotency Configuration setup instead of directly using **'JsonConfig.get().getObjectMapper()**

**Comment by msailes** [comment]
Hi @AlanStill,

Yes I think this makes sense, would you be interested in submitting a PR for this?

Thanks,

**Comment by jeromevdl** [comment]
Using `JsonConfig.get().getObjectMapper()`, you can actually customize the Mapper, add a module, change the config, anything that you can do with an `ObjectMapper`. You need to do this in th constructor of the function before configuring Idempotency.

**Comment by ChilukuriHR** [comment]
I am facing the below issue with powertools Idempotency. can you assist in resolving this.?

Joda date/time type `org.joda.time.DateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-joda" to enable handling (through reference chain: com.amazonaws.services.lambda.runtime.events.S3Event["records"]->java.util.ArrayList[0]->com.amazonaws.services.lambda.runtime.events.models.s3.S3EventNotification$S3EventNotificationRecord["eventTime"])

Thanks in advance.!

**Comment by oscarkof** [comment]
> Using `JsonConfig.get().getObjectMapper()`, you can actually customize the Mapper, add a module, change the config, anything that you can do with an `ObjectMapper`. You need to do this in th constructor of the function before configuring Idempotency.

Hey @jeromevdl thanks for you comment, I think you can improve the official documentation in faq section to avoid this issue, I used for lambda powertools idempotency and this save my day:

```
// Register Joda Module to serialize
        JsonConfig.get().getObjectMapper().registerModule(new JodaModule());
```
