### ISSUE TITLE
Rename MetricsUtils.withMetricLogger to MetricsUtils.withMetricsLogger

### ISSUE THREAD

**Issue by humanzz** [awslabs/aws-lambda-powertools-java#1059]
https://github.com/awslabs/aws-lambda-powertools-java/pull/1000 introduced the wrongly named `MetricsUtils.withMetricLogger`. To be consistent, it should have been called `MetricsUtils.withMetricsLogger`.

Deprecate `MetricsUtils.withMetricLogger` and introduce `MetricsUtils.withMetricsLogger`.

**Comment by jeromevdl** [comment]
fixed with #1060
