### ISSUE TITLE
Update Issue Templates to follow other Powertools runtimes best practices 

### ISSUE THREAD

**Issue by machafer** [awslabs/aws-lambda-powertools-java#1061]
Update Issue Templates to follow other Powertools runtimes best practices(Python & .Net)

- Add maintenance template: [https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/ISSUE_TEMPLATE/maintenance.yml](url)
- Add Share your work template: [https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/ISSUE_TEMPLATE/share_your_work.yml](url)
- Add Documentation Improvements template: [https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/ISSUE_TEMPLATE/documentation_improvements.yml](url)
- Disable Blank issues and Add Ask a general question template; [https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/.github/ISSUE_TEMPLATE/config.yml](url)
- Add missing "triage" label to Documentation template:

**Comment by jeromevdl** [comment]
closed with #1062
