### ISSUE TITLE
Maintenance: Add unit test coverage

### ISSUE THREAD

**Issue by jeromevdl** [awslabs/aws-lambda-powertools-java#1080]
### Summary

Add unit test coverage to get a better visibility on where we can have issues, and improve the coverage where needed.

### Why is this needed?

Lambda Powertools for Java has a decent amount of unit tests but we don't have a clear view on what is well-tested and more important where we can improve. Having the coverage reports will help driving the effort and make sure we minimize the risk of issues.

### Which area does this relate to?

Tests

### Solution

We could use one of the standard frameworks (Jacoco, Cobertura) and deploy the reports to codecov.io just like the Python version does (see https://github.com/awslabs/aws-lambda-powertools-python/blob/79e7b4392a1a0f69bcf627b137c81be45867c587/.github/workflows/python_build.yml#L55)

### Acknowledgment

- [X] This request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-java/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [TypeScript](https://github.com/awslabs/aws-lambda-powertools-typescript/)

**Comment by scottgerring** [comment]
The [powertools for python](https://app.codecov.io/gh/awslabs/aws-lambda-powertools-python) dashboard

**Comment by jeromevdl** [comment]
closed with #1094
