### ISSUE TITLE
ActiveMQ support in validation module

### ISSUE THREAD

**Issue by msailes** [awslabs/aws-lambda-powertools-java#179]
**Is your feature request related to a problem? Please describe.**

Can we add ActiveMQ support in the validation module - https://github.com/aws/aws-lambda-java-libs/pull/185

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pankajagrawal16** [comment]
Should be addressed in https://github.com/awslabs/aws-lambda-powertools-java/pull/757/files

**Comment by jeromevdl** [comment]
Indeed (https://github.com/awslabs/aws-lambda-powertools-java/blob/eb2bb39954c0c2c52b90954ba627747264f4fd8a/powertools-validation/src/main/java/software/amazon/lambda/powertools/validation/internal/ValidationAspect.java#L95), was cover with #757 (as well as RabbitMQ)
