### ISSUE TITLE
RFC: Parameter Injection

### ISSUE THREAD

**Issue by vitodegiosa** [awslabs/aws-lambda-powertools-java#184]
## Key information

* RFC PR: 
* Related issue(s), if known:
* Area: Parameter
* Meet [tenets](https://awslabs.github.io/aws-lambda-powertools-java/#tenets): Yes

## Summary
[summary]: #summary

> Provide an annotation based injection of parameters. A concept similar to the @Value annotation in Spring, backed up by the existing providers for SSM and Secrets Manager

## Motivation
[motivation]: #motivation

> This feature will make it easier and concise to retrieve and use parameters in a declarative way.

## Proposal
[proposal]: #proposal

Annotating a String field into the Lambda handler would result into the field to be populated with the value of the referenced parameter available in one of the possible providers (SSM and Secrets Manager for the time being).

It could look like this:

`@Parameter(name="/powertools-java/sample/simplekey")`
`private String myParam;` 

The annotation can provide options to specify name, provider, transformation, caching

`@Parameter(name="/sample/simplekey", provider="SSM", maxAge=30)`
`private String myParam;`

## Drawbacks
[drawbacks]: #drawbacks

> Why should we *not* do this?
Less transparency in the code

> Do we need additional dependencies? Impact performance/package size?
No

## Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

* **What other designs have been considered? Why not them?**
* **What is the impact of not doing this?**

## Unresolved questions
[unresolved-questions]: #unresolved-questions

> Optional, stash area for topics that need further development e.g. TBD

**Comment by pankajagrawal16** [comment]
Hey @vitodegiosa Sure does sounds like a neat utility to have on top of already provided utilities for fetching secrets/ssm parameters

**Comment by vitodegiosa** [comment]
Feature merged
