### ISSUE TITLE
Lambda powertool SSMProvider is either increasing cold start time or unable to refresh parameters

### ISSUE THREAD

**Issue by deepti-tyagi** [awslabs/aws-lambda-powertools-java#215]
We may need to update some Parameter Store parameters value that are being used in Lambda Function. 
If any parameter is updated while Lambda is in Warm state, it should be able to read the latest values.
I used lambda powertool SSMProvider to achieve the same inside lambda function constructor and inside the lambda handler.

The issue here is; if parameters are read inside the constructor, it does not get refreshed after 1 minute (withMaxAge(60, SECONDS)). And if I read these parameters inside lambda handler method, it increases the cold, warm start time to ~3 times though connection to SSMProvider is initialized only once inside constructor.

**What were you trying to accomplish?**
Trying to read the latest values of the parameters while Lambda is in warm state. The reason to read parameters inside constructor is to reduce the warm start time.

## Expected Behavior
Lambda should be able to read latest values of parameters and it should not impact performance.

## Code Snippet

```
public class CustomHandler implements RequestHandler<Object, Object> {
	private static SSMProvider ssmProvider = null;
	private static Map<String, String> params = null;
	
	public CustomHandler() {
		ssmProvider = DependencyFactory.ssmProvider();
		
		// Parameters are not refreshed after 1 min as configured.
		params = ssmProvider.withMaxAge(60, SECONDS).withDecryption().recursive().getMultiple("/lab/workflow");
	}
	
	@Override
	public Object handleRequest(final Object input, final Context context) {
		// Parameters are refreshed after 1 min as configured but;
		// Cold start time is 3-4 times higher,
		// Warm start time after every minute is 2-3 times higher.
		params = ssmProvider.withMaxAge(60, SECONDS).withDecryption().recursive().getMultiple("/lab/workflow");
	}

}
public class DependencyFactory {
	public static SSMProvider ssmProvider() {
		return ParamManager.getSsmProvider(ssmClient());
	}

	public static SsmClient ssmClient() {
		return SsmClient.builder().credentialsProvider(EnvironmentVariableCredentialsProvider.create())
			.region(region).httpClientBuilder(UrlConnectionHttpClient.builder()).build();
	}
}
```

## Environment

* **Powertools version used**: 1.1.0
* **Packaging format (Layers, Maven/Gradle)**: Java8
* **AWS Lambda function runtime:** Maven

``` Debug Log
{
    "Timestamp": "2020-12-07 22:11:40",
    "RequestId": "7a4c8861-1c4e-4c33-becf-f990404eb3b5",
    "Severity": "DEBUG",
    "Message": "request - Sending Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=ssm.us-east-1.amazonaws.com, encodedPath=/, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent, X-Amz-Target], queryParameters=[])\n"
}
{
    "Timestamp": "2020-12-07 22:11:40",
    "RequestId": "7a4c8861-1c4e-4c33-becf-f990404eb3b5",
    "Severity": "DEBUG",
    "Message": "request - Received successful response: 200\n"
}
```

**Comment by jeromevdl** [comment]
Hi,

Thanks for reporting this.

The constructor won't be called in a warmed function, the call to SSM will be done once during cold start. So whatever the maxAge you set, it doesn't really matter, params will remain the same while the function is warmed.

In the handler, with your code I had the following results:
cold start: 3+ seconds (~3400 ms)
warm start: single-digit ms (~2-3 ms)
warm start after 1 min (reload params): ~200-300 ms

I replaced powertools-param with an similar call to ssm:

- In the constructor:

`ssmClient = SsmClient.builder()
                .httpClientBuilder(UrlConnectionHttpClient.builder())
                .credentialsProvider(EnvironmentVariableCredentialsProvider.create())
                .region(Region.of(System.getenv(SdkSystemSetting.AWS_REGION.environmentVariable())))
                .build();`

- In the handler:

`GetParametersByPathResponse params = ssmClient.getParametersByPath(GetParametersByPathRequest.builder().path("/powertools-java/sample").recursive(true).withDecryption(true).build());`

And had exactly the same results (few ms difference):
cold start: 3+ seconds (~3300 ms)
warm start: 200-300 ms (each time)

Unfortunately, we cannot improve the call to SSM itself, but thanks to the cache, it reduces the time from 200-300ms to 2-3ms during the time of the cache. Then, you need to find the best TTL for your use case.

**Comment by deepti-tyagi** [comment]
Thanks @jeromevdl for taking out some time for this.
Yes, I agree cache does help to improve performance during warm state. 

As a workaround, we can also force a cold restart on Lambda function by changing an environment variable whenever there is an update on SSM parameter. We can also avoid additional cold start time using this approach.

My question is, does it impact any existing lambda invocations that are in progress, in any way?

**Comment by jeromevdl** [comment]
Functions currently running are not impacted by an update, they will finish with current version/configuration.

**Comment by deepti-tyagi** [comment]
Thanks @jeromevdl for confirming.

**Comment by pankajagrawal16** [comment]
@deepti-tyagi I believe we can close this issue for now based on above discussion. Thanks for using powertools. Feel free to open an issue in case of any questions/issues/feedback. :)
