### ISSUE TITLE
isDebugEnabled() returning false when debug enabled through env var

### ISSUE THREAD

**Issue by asmith-r7** [awslabs/aws-lambda-powertools-java#293]
I have several sections in my debug wrapped in the logger.isDebugEnabled()
What I noticed is that setting the log level to debug through the env var LOG_LEVEL causes these log lines not to appear. This seems like a bug to me.

## Expected Behavior

isDebugEnabled should return true.

## Steps to Reproduce (for bugs)

1. Configure logging via config to be INFO
2. Override to DEBUG via LOG_LEVEL env var

## Environment

* **Powertools version used**:
* **Packaging format (Layers, Maven/Gradle)**:
* **AWS Lambda function runtime:**
* **Debugging logs**

> [How to enable debug mode](https://awslabs.github.io/aws-lambda-powertools-java/#debug-mode)**

```text
# paste logs here
```

**Comment by pankajagrawal16** [comment]
Thanks @asmith-r7 For reporting the issue. I did some digging and Can see that the LOG_LEVEL env variable gets overridden by system property back to INFO. 

Which means that either we will have to find another name for our environment variable to be something like `POWERTOOLS_LOG_LEVEL` instead.

or we will have to support it via java tool options via 

 `JAVA_TOOL_OPTIONS: -DLOG_LEVEL=INFO. `

In terms of user experience, I believe having a different environment variable names is better than the later.

**Comment by pankajagrawal16** [comment]
Something like this https://github.com/awslabs/aws-lambda-powertools-java/compare/log-level?expand=1

**Comment by pankajagrawal16** [comment]
Available in [1.3.0](https://github.com/awslabs/aws-lambda-powertools-java/releases/tag/v1.3.0) now
