### ISSUE TITLE
Spotbugs issues when using Powertools

### ISSUE THREAD

**Issue by humanzz** [awslabs/aws-lambda-powertools-java#298]
My team has a Gradle setup in our Lambda. We have Spotbugs enabled and failing our builds on finding issues. Once we added the Powertools dependencies Spotbugs picked up a few code issues in Powertools which I'm reporting below.

**What were you trying to accomplish?**
Use Powertools Logging, Metrics and Tracing.

## Expected Behavior

Build to succeed without issues once dependencies were included

## Current Behavior

Spotbugs picks up issues in Powertools code

![Screenshot 2021-02-25 at 10 19 17](https://user-images.githubusercontent.com/5001/109139846-e2715080-7753-11eb-82d0-8ec5905bc3f0.png)

## Environment

* **Powertools version used**: 1.2.0
* **Packaging format (Layers, Maven/Gradle)**: Gradle, Spotbugs
* **AWS Lambda function runtime:** Java 11

**Comment by pankajagrawal16** [comment]
Available in [1.3.0](https://github.com/awslabs/aws-lambda-powertools-java/releases/tag/v1.3.0) now
