### ISSUE TITLE
Build failed - Could not find artifact com.sun:tools:jar

### ISSUE THREAD

**Issue by gyoga99** [awslabs/aws-lambda-powertools-java#320]
I added mvn plugin and dependencies as documented here. 

https://awslabs.github.io/aws-lambda-powertools-java/utilities/sqs_large_message_handling/

I am using  `AdoptOpenJDK (build 11.0.8+10)`

I am getting this error when I run `mvn package` 

Execution default of goal org.codehaus.mojo:aspectj-maven-plugin:1.11:compile failed: Plugin org.codehaus.mojo:aspectj-maven-plugin:1.11 or one of its dependencies could not be resolved: Could not find artifact com.sun:tools:jar:11.0.8 at specified path

Can you please let me know if there is anything else I need to do?

**Comment by pankajagrawal16** [comment]
Hi @gyoga99 I believe this is because of already referenced issue https://github.com/awslabs/aws-lambda-powertools-java/issues/50

Try using plugin as documented in issue.

```
                 <groupId>com.nickwongdev</groupId>
                <artifactId>aspectj-maven-plugin</artifactId>
                <version>1.12.1</version>
```

instead of 

```

            <groupId>org.codehaus.mojo</groupId>
             <artifactId>aspectj-maven-plugin</artifactId>
             <version>1.11</version>
```

This is also reference in our docs here https://awslabs.github.io/aws-lambda-powertools-java/#install, but I do see that we can probably improve the docs to make it more explicit for all the utilities installation instructions well.

Let me know if this fixes your issue?

**Comment by gyoga99** [comment]
Thanks @pankajagrawal16!
That issue got resolved now.
When I running my unit test class. I am seeing `java.lang.NoClassDefFoundError` for `SqsLargeMessageAspect.class` 
Dependencies added in pom.xml-
    <dependency>
      <groupId>software.amazon.lambda</groupId>
      <artifactId>powertools-sqs</artifactId>
      <version>1.3.0</version>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>amazon-sqs-java-extended-client-lib</artifactId>
      <version>1.1.0</version>
    </dependency>

**Comment by pankajagrawal16** [comment]
> Thanks @pankajagrawal16!
> That issue got resolved now.
> When I running my unit test class. I am seeing `java.lang.NoClassDefFoundError` for `SqsLargeMessageAspect.class`
> Dependencies added in pom.xml-
> 
> software.amazon.lambda
> powertools-sqs
> 1.3.0
> 
> 
> com.amazonaws
> amazon-sqs-java-extended-client-lib
> 1.1.0

Hmm this is Strange, What does you pom.xml looks like? Possible to share here ?

**Comment by gyoga99** [comment]
I see this warning during `mvn clean package`

=========================================
[INFO] Showing AJC message detail for messages of types: [error, warning, fail]
[WARNING] bad version number found in /.m2/repository/org/aspectj/aspectjrt/1.9.6/aspectjrt-1.9.6.jar expected 1.9.2 found 1.9.6
        <unknown source file>:<no line information>

[WARNING] advice defined in software.amazon.lambda.powertools.sqs.internal.SqsMessageBatchProcessorAspect has not been applied [Xlint:adviceDidNotMatch]
        /.m2/repository/software/amazon/lambda/powertools-sqs/1.3.0/powertools-sqs-1.3.0.jar!software/amazon/lambda/powertools/sqs/internal/SqsMessageBatchProcessorAspect.class:0 
==========================================
pom.xml entries related to SQS Large message processing.

<plugin>
        <groupId>com.nickwongdev</groupId>
        <artifactId>aspectj-maven-plugin</artifactId>
        <version>1.12.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
          <complianceLevel>1.8</complianceLevel>
          <aspectLibraries>
            <aspectLibrary>
              <groupId>software.amazon.lambda</groupId>
              <artifactId>powertools-sqs</artifactId>
            </aspectLibrary>
          </aspectLibraries>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

<dependency>
      <groupId>software.amazon.lambda</groupId>
      <artifactId>powertools-sqs</artifactId>
      <version>1.3.0</version>
    </dependency>
    <dependency>
      <groupId>com.amazonaws</groupId>
      <artifactId>amazon-sqs-java-extended-client-lib</artifactId>
      <version>1.1.0</version>
    </dependency>

**Comment by pankajagrawal16** [comment]
Hi @gyoga99 

Did you manage to solve this? You pom entries looks correct. Also the warning that you are seeing is strange, coz this should have worked. 

Since this warning seems to be coming from your unit test, can you try adding below test scoped dependency to your pom  as well ?


```
 <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
            <scope>test</scope>
        </dependency>
```

**Comment by pankajagrawal16** [comment]
Hi @gyoga99

Did you manage to solve this?

**Comment by pankajagrawal16** [comment]
Hi @gyoga99,

Wondering if the issue is solved now?

**Comment by gyoga99** [comment]
@pankajagrawal16 I have not tried this. Will try and update you.

**Comment by gyoga99** [comment]
Resolved this error. The issue was with mocking.

Thanks!
