### ISSUE TITLE
Add correlation_id support similar to python powertools

### ISSUE THREAD

**Issue by pankajagrawal16** [awslabs/aws-lambda-powertools-java#322]
**Is your feature request related to a problem? Please describe.**

Similar to python version, add support for capturing correlation id https://github.com/awslabs/aws-lambda-powertools-python/pull/321

https://github.com/awslabs/aws-lambda-powertools-python/issues/9

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dmahapatro** [comment]
I believe `correlation_id` will also help adding feature similar to [stop infinite loop middleware](https://github.com/getndazn/dazn-lambda-powertools/tree/master/packages/lambda-powertools-middleware-stop-infinite-loop)
