### ISSUE TITLE
feat: Support for Boolean and Number type as value in TracingUtils putAnnotation

### ISSUE THREAD

**Issue by dmahapatro** [awslabs/aws-lambda-powertools-java#421]
**Is your feature request related to a problem? Please describe.**
I came across a minor feature missing in `TracingUtils`. [XRay SDK](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-segment.html#xray-sdk-java-segment-annotations) supports recording annotations as:

 - Keys – Up to 500 alphanumeric characters. No spaces or symbols except underscores.
 - Values – Up to 1,000 Unicode characters.

With `key` being a string and `value` can be a Boolean, Number, or String value. 

However, `TracingUtils` [just supports value as String](https://github.com/awslabs/aws-lambda-powertools-java/blob/master/powertools-tracing/src/main/java/software/amazon/lambda/powertools/tracing/TracingUtils.java#L37), there is no support for Number, Boolean. 

**Describe the solution you'd like**
Adding support for `Number` & `Boolean` like: 

```java
public static void putAnnotation(String key, Number value) {
  AWSXRay.getCurrentSubsegmentOptional()
    .ifPresent(segment -> segment.putAnnotation(key, value));
}
```

**Describe alternatives you've considered**
This is not a blocker because I can use `String.valueOf(myIntValue)`

**Additional context**

**Comment by pankajagrawal16** [comment]
Available in https://github.com/awslabs/aws-lambda-powertools-java/releases/tag/v1.6.0
