### ISSUE TITLE
Lazy loading of default SQSClient in order to make it work in quarkus /graalvm native

### ISSUE THREAD

**Issue by argenstijn** [awslabs/aws-lambda-powertools-java#472]
**Is your feature request related to a problem? Please describe.**
Use powertools within quarkus 2.0.2 and graalvm 21.1

**Describe the solution you'd like**
Currently when using this AWS tool within quarkus (2.0.2 with graalv 21.1) you get the following exception:

`Error: Classes that should be initialized at run time got initialized during image building:
 software.amazon.awssdk.core.retry.backoff.FullJitterBackoffStrategy the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why software.amazon.awssdk.core.retry.backoff.FullJitterBackoffStrategy got initialized use --trace-class-initialization=software.amazon.awssdk.core.retry.backoff.FullJitterBackoffStrategy
com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 software.amazon.awssdk.core.retry.backoff.FullJitterBackoffStrategy the class was requested to be initialized at run time (from feature io.quarkus.runner.AutoFeature.beforeAnalysis). To see why software.amazon.awssdk.core.retry.backoff.FullJitterBackoffStrategy got initialized use --trace-class-initialization=software.amazon.awssdk.core.retry.backoff.FullJitterBackoffStrategy
	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)`

Which is caused by the fact that the default SqsClient is initilazed even if you override it later. Could you please do lazy loading of the SqsClient. That way we can fix this problem very easily.

public final class SqsUtils {
/////
private static SqsClient client = SqsClient.create();   <-- always loaded

**Comment by pankajagrawal16** [comment]
Hi @argenstijn Thanks for opening the issue. Reason we initialise this static so that it can be done during function init phase of lambda execution model. 

Is there a way to configure graalvm not to complain about it (without knowing much about graalvm ecosystem currently)? Something on the similar lines? https://stackoverflow.com/questions/60654455/how-to-fix-try-avoiding-to-initialize-the-class-that-caused-initialization-wit

**Comment by argenstijn** [comment]
Of course: 

--initialize-at-run-time=software.amazon.lambda.powertools.sqs.SqsUtils

**Comment by pankajagrawal16** [comment]
> Of course:
> 
> --initialize-at-run-time=software.amazon.lambda.powertools.sqs.SqsUtils
> 
> But the 'problem' is also that the default SQS is created even when you override it. In this situation it just unnecessary to load the default SQS.

Yeah I agree. I will configure it to lazy load, just wanted to see first that its not a blocker to make it run with graalv and there is a workaround the error.

**Comment by argenstijn** [comment]
Thanks. And it works in quarkus.

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by pankajagrawal16** [comment]
Fixed in https://github.com/awslabs/aws-lambda-powertools-java/releases/tag/v1.7.2
