### ISSUE TITLE
Unit Tests are missing from the project

### ISSUE THREAD

**Issue by scottmk** [awslabs/aws-lambda-powertools-java#504]
The README has the following text:
> ## Unit tests
> 
> Tests are defined in the `HelloWorldFunction/src/test` folder in this project.
> 
> ```bash
> example$ cd HelloWorldFunction
> HelloWorldFunction$ gradle test
> ```

But there is no such folder `HealloWorldFunction/src/test`

**What were you trying to accomplish?**

## Expected Behavior
There should be a `HealloWorldFunction/src/test` folder with unit tests

## Current Behavior
There is no such folder that I can find

## Possible Solution
Add the unit tests to the repository, if they exist, or remove the Unit Test section from the README if they do not

**Comment by pankajagrawal16** [comment]
Hi @scottmk,

Thanks for opening the issue. The example project is deprecated and probably will be removed from the project. Its sometimes used for internal troubleshooting if needed.

If you are looking for sample project implementing powerools, I will recommend to create one via 

```
    sam init --location gh:aws-samples/cookiecutter-aws-sam-powertools-java
```
Also documented here: https://awslabs.github.io/aws-lambda-powertools-java/#install

This way you will get the latest project pre configured with powertools core utility. Let me know if you face any issues.

**Comment by pankajagrawal16** [comment]
I am closing this for now. Probably we will be removing the example project from the repo and have a separate example repo on aws-samples
