### ISSUE TITLE
Idempotency utility support similar to python version

### ISSUE THREAD

**Issue by pankajagrawal16** [awslabs/aws-lambda-powertools-java#515]
**Is your feature request related to a problem? Please describe.**

Idempotency utility support similar to python version https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/idempotency/

**Describe the solution you'd like**
Idempotency utility support similar to python version https://awslabs.github.io/aws-lambda-powertools-python/latest/utilities/idempotency/

**Describe alternatives you've considered**
Implementing idempotency ourselves

**Additional context**

**Comment by pankajagrawal16** [comment]
@jeromevdl Is working on this now.

**Comment by hasan-imam** [comment]
Is there an ETA for this? We prepared a similar implementation to make our functions idempotent and we're planning to apply on a bunch of our systems. But we'd rather adopt the one coming from power-tools than our homemade version; they look pretty similar.

Also would it be possible to emit some metrics around number of requests de-duped, various error counts etc.?

**Comment by pankajagrawal16** [comment]
@jeromevdl has started looking into it. 

> Also would it be possible to emit some metrics around number of requests de-duped, various error counts etc.?

This can be an interesting thing to support. @heitorlessa What do you think? Has it been discussed for python one?
