### ISSUE TITLE
Gradle plug-in for compile-time weave (CTW) 

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-java#58]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Please include a gradle plugin for setting up the compile-time weave (CTW). I think this would be a far more popular option than maven. 

**Describe alternatives you've considered**

**Additional context**

**Comment by msailes** [comment]
Hi Michael,

We'll have a look at this, thanks.

Mark

**Comment by michaelbrewer** [comment]
@msailes thanks once we have this. It will be easy to incorporate this into the majority of java lambda projects using gradle.

**Comment by pankajagrawal16** [comment]
Closed by #147

**Comment by michaelbrewer** [comment]
Thanks @pankajagrawal16 !
