### ISSUE TITLE
Feature request: Allow setting a custom S3 client when using LargeMessageHandling

### ISSUE THREAD

**Issue by qtdzz** [awslabs/aws-lambda-powertools-java#597]
**Is your feature request related to a problem? Please describe.**
Currently the large message handler uses default AmazonS3 client to download client. It means the lambda execution IAM role must have S3 read permissions. The problem is when the S3 bucket is owned by another owner, they provide us the access via an IAM role and ask us to assume that role to read S3 content. Right now, we can't pass a custom S3 client (with assumed credentials) into the LargeMessageHandler.

**Describe the solution you'd like**
Be able to provide a custom AmazonS3 client for large message handling

**Comment by pankajagrawal16** [comment]
Released as part of https://github.com/awslabs/aws-lambda-powertools-java/releases/tag/v1.8.0
