### ISSUE TITLE
Using Maven Lombok and Aspect doesn't compile

### ISSUE THREAD

**Issue by mlefebvre-deblecx** [awslabs/aws-lambda-powertools-java#630]
When trying to run mvn package the project that include some Aspect (ex: powertool-logging) and also using lombok as dependency break the compilation.

**I'm trying to use the powertool with lombok**

## Expected Behavior
Should not break the build, or have something in the documentation that explains how to make them work together

## Possible Solution
Add documentation explaining how to fix it, or use another mechanism to compile de aspect.

## Steps to Reproduce (for bugs)
1. Create a new project
2. Add lombok dependency
3. Add powertools-loggin dependency
4. Add powertools-loggin aspect plugin
5. Run mvn package

## Environment

* **Powertools version used**: Latest
* **Packaging format (Layers, Maven/Gradle)**: Maven
* **AWS Lambda function runtime:** Java 11
* **Debugging logs**
[WARNING] You aren't using a compiler supported by lombok, so lombok will not work and has been disabled.
Your processor is: org.aspectj.org.eclipse.jdt.internal.compiler.apt.dispatch.BatchProcessingEnvImpl
Lombok supports: OpenJDK javac, ECJ
	<unknown source file>:<no line information>

> [How to enable debug mode](https://awslabs.github.io/aws-lambda-powertools-java/#debug-mode)**

```text
# paste logs here
```

**Comment by msailes** [comment]
Hi, do you have a public project which reproduces the problem?

**Comment by mlefebvre-deblecx** [comment]
@msailes Just do a `mvn clean package` of this project: 

https://github.com/mlefebvre-deblecx/powertools-lombok

If we do a mvn package just after it seems to fix the bug, but it comes back after a clean and for bigger project it does fix it.

**Comment by pankajagrawal16** [comment]
@msailes We you looking into this issue? Any further insights what is happening ?

**Comment by kozub** [comment]
Hey @msailes, I quickly checked an issue that you've raported. Looks that it is not directly related to aws-lambda-powertools-java. The main issue there is related to using Aspectj with Lombok, as both of them needs to add some `secret sause` during the compilation. You can use technic that is called weaving.

I've tried code that you'd provided (thanks for that!) and after changing plugin config in pom.xml to: 

```
<configuration>
                    <sources/>
                    <weaveDirectories>
                        <weaveDirectory>${project.build.directory}/classes</weaveDirectory>
                    </weaveDirectories>
                    <source>1.8</source>
                    <target>1.8</target>
                    <complianceLevel>1.8</complianceLevel>
                    <aspectLibraries>
                        <aspectLibrary>
                            <groupId>software.amazon.lambda</groupId>
                            <artifactId>powertools-logging</artifactId>
                        </aspectLibrary>
                    </aspectLibraries>
                </configuration>
``` 
it works. 

Could you please verify with your orginal source code that it works as well? 

Some details about this issue: 
https://palesz.wordpress.com/2011/12/03/howto-maven-lombok-and-aspectj-together/
https://www.mojohaus.org/aspectj-maven-plugin/examples/weaveDirectories.html

**Comment by msailes** [comment]
@pankajagrawal16 I imagine this case will be fairly common, should we update the docs to include it?

I'm not sure where we'd put it.

**Comment by kozub** [comment]
@pankajagrawal16 @msailes  - Does it make any sense to add FAQ  / other new section to docs for that kind of issues?

**Comment by msailes** [comment]
@kozub I think so, would you be in a position to submit a PR?

**Comment by kozub** [comment]
Sure, I can do it. I will do my best to provide required changes tomorrow.

**Comment by pankajagrawal16** [comment]
Its available here now https://awslabs.github.io/aws-lambda-powertools-java/FAQs/

**Comment by pankajagrawal16** [comment]
@mlefebvre-deblecx Let us know if this helps and fixes the issue you were facing. thanks @kozub for contribution.
