### ISSUE TITLE
RFC: Allow filtering logEvent output

### ISSUE THREAD

**Issue by dgomesbr** [awslabs/aws-lambda-powertools-java#66]
**Is your feature request related to a problem? Please describe.**

It's not, it's an enhancement

**Describe the solution you'd like**

Considering that `logEvent` param exists over `@PowertoolsLogging`, we should provide an option include only/exclude fields from the event log record itself, as such: 
* AllowedFields: Set<...> Only log items contained on the List/Set
* PreventLogFields: Set<...>: Only log items not matching the List/Set
....

**Describe alternatives you've considered**

There are no alternatives when using LogEvent

**Additional context**

**Comment by pankajagrawal16** [comment]
Hey @dgomesbr It definitely sounds like an interesting idea.

Could you please shed some more inputs on your thoughts here ? Like What and how you think of it behaving on nested payload etc ?

**Comment by dgomesbr** [comment]
@pankajagrawal16 as an user concerned with data being logged, but also conscious about logging, I would like to either pass a `Predicate<? super String> predicate` where users could pass whatever predicate they want, and maybe apply at `PowertoolsLogger.java` implementation level. 

Does that adds up?

**Comment by msailes** [comment]
I was thinking about this. I think nested payloads makes this harder.

Could the user pass an implementation class name, we'd instantiate it and use it to do the filtering.

**Comment by pankajagrawal16** [comment]
I have created a PR which will let clients override the default object mapper used for serializing the event. This will also let client decide and how and what they want to log the event. https://github.com/awslabs/aws-lambda-powertools-java/pull/287

@dgomesbr I believe we can close this issue based on this ability as well.  Thoughts?

**Comment by dgomesbr** [comment]
LGTM

**Comment by pankajagrawal16** [comment]
Available in [1.3.0](https://github.com/awslabs/aws-lambda-powertools-java/releases/tag/v1.3.0) now
