### ISSUE TITLE
Documentation mentions metrics, but no code is available just yet

### ISSUE THREAD

**Issue by dgomesbr** [awslabs/aws-lambda-powertools-java#67]
**What were you initially searching for in the docs?**

https://awslabs.github.io/aws-lambda-powertools-java/ mentions: "Powertools is a suite of utilities for AWS Lambda Functions that makes tracing with AWS X-Ray, structured logging and creating custom metrics asynchronously easier."

But no metric module has been published yet.

**Is this related to an existing part of the documentation? Please share a link**
https://awslabs.github.io/aws-lambda-powertools-java/

**Describe how we could make it clearer**
Tell that metric module is coming.

**If you have a proposed update, please share it here**

**Comment by pankajagrawal16** [comment]
Thanks for opening an issue @dgomesbr . We can definitely improve the docs suggesting the [metrics](https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-cloudwatch-launches-embedded-metric-format/)  will coming soon.
