### ISSUE TITLE
When is the next release with log4j 17.1 planned?

### ISSUE THREAD

**Issue by asmith-r7** [awslabs/aws-lambda-powertools-java#681]
Hey, I see you have patched log4j in master. I am just wondering if you are planning to cut a release anytime soon. We have a number of lambdas which we would like to patch and being able to just bump this library would be the simpler approach.

**Comment by msailes** [comment]
Hi @asmith-r7,

This will be done today.

Thanks,

**Comment by asmith-r7** [comment]
Awesome, thanks.

And thanks for the great library!

**Comment by msailes** [comment]
This is now available on maven central.
