### ISSUE TITLE
Gradle: Set java target level in cookiecutter and docs

### ISSUE THREAD

**Issue by michaelbrewer** [awslabs/aws-lambda-powertools-java#702]
**What were you trying to accomplish?**

Building the gradle project using jdk 17

## Expected Behavior

Project should compile with target level of java 11 or java 1.8

## Current Behavior

Sam template example fails

```
Running JavaGradleWorkflow:GradleBuild

Build Failed
Error: JavaGradleWorkflow:GradleBuild - Gradle Failed: [error] target level should be in '1.1'...'1.8','9'...'16' (or '5.0'..'16.0') or cldc1.1: 17
```

## Possible Solution

Update gradle example

```gradle
plugins{
    id 'java'
    id 'io.freefair.aspectj.post-compile-weaving' version '6.3.0'
}

repositories {
    mavenCentral()
}

dependencies {
    aspect 'software.amazon.lambda:powertools-logging:1.10.2'
    aspect 'software.amazon.lambda:powertools-tracing:1.10.2'
    aspect 'software.amazon.lambda:powertools-metrics:1.10.2'

    implementation 'com.amazonaws:aws-lambda-java-core:1.2.1'
    implementation 'com.amazonaws:aws-lambda-java-events:3.11.0'

    implementation 'org.apache.logging.log4j:log4j-api:2.17.1'
    implementation 'org.apache.logging.log4j:log4j-core:2.17.1'

    testImplementation 'junit:junit:4.13.2'
}

sourceCompatibility = 11
targetCompatibility = 11

```

## Steps to Reproduce (for bugs)
1. `sam init --location gh:aws-samples/cookiecutter-aws-sam-powertools-java`
2. Select gradle and java11 (with java 17 installed locally)
3. run `sam build`

## Environment

* **Powertools version used**: 1.10.2
* **Packaging format (Layers, Maven/Gradle)**: Gradle
* **AWS Lambda function runtime:** Java 11 (or Java 1.8)

**Comment by pankajagrawal16** [comment]
Thanks for spotting and fixing the docs and config @michaelbrewer

**Comment by michaelbrewer** [comment]
hopefully java 17 runtime is coming out soon :)
