### ISSUE TITLE
Explain gotchas related to testing and @Tracing

### ISSUE THREAD

**Issue by GuyJackson** [awslabs/aws-lambda-powertools-java#727]
When adding Lambda Powertools Java to my project and I have annotated my handler method with `@Tracing`.

When a basic unit test is run I get an error "_SegmentNotFound"_. 

I think you may be able to create a segment in a test like `AWSXRay.beginSegment("handleRequest")` but that is not what I want to be doing.

It would be helpful if the documentation could explain what to do in this testing scenario.

**Comment by pankajagrawal16** [comment]
Definitely, `AWSXRay.beginSegment` is needed for test cases. Fair point regarding documentation, we can update docs to make it but more clear

**Comment by pankajagrawal16** [comment]
Hey @GuyJackson , Docs are now updated to with recommendations for testing. https://awslabs.github.io/aws-lambda-powertools-java/core/tracing/#testing-your-code

**Comment by GuyJackson** [comment]
Great thank you @pankajagrawal16 will the recommendations a go.
