### ISSUE TITLE
Send messages to the DLQ before deleting from SQS

### ISSUE THREAD

**Issue by VictorJuliani** [awslabs/aws-lambda-powertools-java#729]
**Is your feature request related to a problem? Please describe.**

I came across a problem where messages were failing and throwing exceptions, but they weren't sent to the DLQ. They were consumed as successful.

After investigation, I found out that the DLQ#SendMessage call from PowerTools was failing due to a missing KMS permission in my lambda.

That caused some messages to be lost from the queues.

**Describe the solution you'd like**

1. Update the documentation to point out that Encrypt/Decrypt and GenerateDataKey* permissions are required if the SQS is encrypted (at least it's not documented [here](https://awslabs.github.io/aws-lambda-powertools-java/utilities/batch/#iam-permissions))
2. Perform the DLQ#SendMessage call **before** the SQS#DeleteMessage ([code ref](https://github.com/awslabs/aws-lambda-powertools-java/blob/master/powertools-sqs/src/main/java/software/amazon/lambda/powertools/sqs/internal/BatchContext.java#L97-L99)) to make sure the message won't be lost in case of any DLQ misconfiguration.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by pankajagrawal16** [comment]
Thanks for opening the issue @VictorJuliani . fair points.
