### ISSUE TITLE
Move examples from project to aws-samples / aws-lambda-powertools-examples

### ISSUE THREAD

**Issue by pankajagrawal16** [awslabs/aws-lambda-powertools-java#732]
**What were you initially searching for in the docs?**

[example](https://github.com/awslabs/aws-lambda-powertools-java/tree/master/example) folder in project is not upto date and is hard for users to see full working examples of different utilities provided by project. Presence of folder just adds confusion.

Move all the examples to https://github.com/aws-samples/aws-lambda-powertools-examples/tree/main/java/ instead with fully working examples for sam project which can be deployed easily to check the utilities. 

Once such example of sqs batch utility already exists today

**Is this related to an existing part of the documentation? Please share a link**

**Describe how we could make it clearer**

**If you have a proposed update, please share it here**

**Comment by kozub** [comment]
Hey @pankajagrawal16  - I will take care of migrating examples that are still in this repository: 

```
Parameters
Validation
```

**Comment by pankajagrawal16** [comment]
Thanks for bringing this to completion @kozub 🙌
