### ISSUE TITLE
docs: change project name to "AWS Lambda Powertools for Java" 

### ISSUE THREAD

**Issue by saragerion** [awslabs/aws-lambda-powertools-java#779]
## Description of the improvement

**Summary of the proposal**

Change project name being referenced from these versions:

- AWS Lambda Powertools (Java)
- Lambda Powertools Java
- AWS Lambda Powertools Java

To this: 
AWS Lambda Powertools for Java

**[See related RFC for more information](https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/80)**

**How, where did you look for information**

- Readme files (root folder, nested project folders)
- Mkdocs files in `docs`
- Code
- ...

We probably need to do a text search in the whole repo.

**Missing or unclear documentation**

Inconsistent naming convention, see related RFC.

**Improvement**

A consistent name throught the project.

### Related existing documentation
N/A

### Related issues, RFCs

https://github.com/awslabs/aws-lambda-powertools-roadmap/issues/80

**Comment by kozub** [comment]
Hey Team! I will take care of this issue.

**Comment by jeromevdl** [comment]
No more AWS Lambda Powertools Java or similar, we can close this one.
