### ISSUE TITLE
RFC: Provide logger instance upon using @PowertoolsLogging

### ISSUE THREAD

**Issue by dgomesbr** [awslabs/aws-lambda-powertools-java#80]
## Key information

* RFC PR: (leave this empty)
* Related issue(s), if known: This will likely be renamed if #68 pass.
* Area: (i.e. Tracer, Metrics, Logger, etc.) Logger
* Meet [tenets](https://awslabs.github.io/aws-lambda-powertools-java/#tenets): (Yes/no) Yes, to all of them

## Summary
[summary]: #summary

This is a lean and clean way to provide consistency on what we require from users in terms of logging. I might want to break this into two separate aspects, as the implementation and the facade, but since we're using Log4J2, I'll open this, and maybe consider a different timeline for the proxy one (Log4J2 over Slf4J).

Consider https://projectlombok.org/features/log, whenever the user interacts with the annotation, an explicit instance of the object is created on users behalf to be used. This makes the declaration, import collision, qualifying the correct import in the hands of the library instead of the user, pushing again convention over configuration.

## Motivation
[motivation]: #motivation

This is a simplified way of adding a logger to existing functions. This also helps the user to adhere to [EMF](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html) and makes it straight forward.

## Proposal
[proposal]: #proposal

> This is the bulk of the RFC.

- [ ] Introduce a logger instance when added to a class
- [ ] Introduce a logger local variable when adding to a method
- [ ] Update the documentation to remove existing logging declarations 

> This should get into specifics and corner-cases, and include examples of how the feature is used. Any new terminology should be defined here.

None, only hiding implementation details.

## Drawbacks
[drawbacks]: #drawbacks

None so far.

> Why should we *not* do this?
Convention over configuration has to have a line when it's too much. I don't believe this will likely cross that line, as we're requiring the users to adopt our Log4J2 instance anyway.

> Do we need additional dependencies? Impact performance/package size?
We don't. This will be an implementation of current ask from users, which is create the local `logger` instance in their classes.

## Rationale and alternatives
[rationale-and-alternatives]: #rationale-and-alternatives

* **What other designs have been considered? Why not them?**
* **What is the impact of not doing this?** 
Users are still required to declare themselves the logger instance

## Unresolved questions
[unresolved-questions]: #unresolved-questions

1. What if the user is already using other logging library? How do address that in this new RFC? How does that works today?

> Optional, stash area for topics that need further development e.g. TBD

**Comment by pankajagrawal16** [comment]
Hey @dgomesbr Thanks for opening an RFC.

I have few immediate questions/comments on this:

- Are you thinking that annotation should work like that from lombok in the sense that it should modify byte code to generate log fields for user or just exposing an api from power tool to provide access to logger instance ? 
- If its the former, my concerns are how would the IDE experience look like? Lombok has plugin support in IDE like intellij etc. 
- Goal of powertools logging annotation is to take away heavy lifting of injecting information from lambda context. It's not meant to replace current logging configuration in your lambda functions.  You can still use lombok in your lambda functions to make it generate log4j2 logger instance if you want to. As of today the annotation only take effect when use on lambda handleRequest method.

Those are my thoughts around it.

I would still be ok to consider exposing an api method which could give you access to a logger instance, something like `PowertoolsLogger.get()` and that gives you access to a logger from log4j2, although I am not sure how much value it adds.

**Comment by dgomesbr** [comment]
Fair consideration. My thoughts were if we're pushing the Json Schema, the Log4J2 as best practice, why not generate the log instance itself.

Since bytecode is generated at design time, and not runtime, also don't foresee issues with the performance.
Oth, great points on the IDE support, I guess I have mixed feelings on that.

Maybe then expose this as a member annotation? `@LoggerInstance` ?
Or maybe we drop it altogether.

**Comment by pankajagrawal16** [comment]
> Fair consideration. My thoughts were if we're pushing the Json Schema, the Log4J2 as best practice, why not generate the log instance itself.
> 
> Since bytecode is generated at design time, and not runtime, also don't foresee issues with the performance.
> Oth, great points on the IDE support, I guess I have mixed feelings on that.
> 
> Maybe then expose this as a member annotation? `@LoggerInstance` ?
> Or maybe we drop it altogether.

`@LoggerInstance` annotation is an option but I am still doubtful on the value that it will add as the only purpose of it will be to provide logger instance and then clients are free to choose any code generators library like lombok for example. I think it at this point it deviates from our [tenets](https://awslabs.github.io/aws-lambda-powertools-java/#tenets) as well. At this point, I am tempted to  drop it altogether.

So if you agree with this, feel free to close the issue or else let us know the thoughts further :)
