### ISSUE TITLE
(internal) GitHub build fails when using git-revision-date plugin in mkdocs

### ISSUE THREAD

**Issue by jeromevdl** [awslabs/aws-lambda-powertools-java#855]
After the apparition of a [cve](https://github.blog/2022-04-12-git-security-vulnerability-announced/) and a correction pushed by git, we had an [error](https://github.com/actions/checkout/issues/766) when building the doc:

> Error: fatal: unsafe repository ('/docs' is owned by someone else)

A git command (`git log -n 1 --date=short`) is issued by the _git-revision-date_ plugin (see [here](https://github.com/zhaoterryy/mkdocs-git-revision-date-plugin/blob/dead44ba484fdf5fe4707ff6c19f0b313569e4f1/mkdocs_git_revision_date_plugin/util.py#L9)) within the mkdocs container and we cannot apply the workaround `git config --global --add safe.directory ...` in the container. 

We are removing the plugin temporarily (#853) to make the build work.

## Expected Behavior
Using the plugin should work (the git log command performed by the plugin should not failed)

## Current Behavior
The git command issued by the plugin fails.

## Possible Solution
- Removing the plugin for the moment.
- Will also open an [issue](https://github.com/zhaoterryy/mkdocs-git-revision-date-plugin/issues/20) on https://github.com/zhaoterryy/mkdocs-git-revision-date-plugin

## Steps to Reproduce (for bugs)
- Add the plugin _git-revision-date_ in mkdocs.yml
- Let Github Actions run the build

**Comment by msailes** [comment]
@rubenfonseca, @heitorlessa Python seems to be using this plugin without any issues. Was this a problem for you? Did you have to do anything to fix it?

**Comment by heitorlessa** [comment]
You have to install it, here's our Dockerfile so `make docs-local-docker` and `make build-docs-website` work: https://github.com/awslabs/aws-lambda-powertools-python/blob/develop/docs/Dockerfile#L2

**Comment by jeromevdl** [comment]
closed with #1066
